### ISSUE TITLE
Release updated pypi package

### ISSUE THREAD

**Issue by nikole-dunixi** [paul-nelson-baker/python-qtest-library#2]
Currently no CI/CD is setup, and probably isn't necessary. If demand picks up, I can create an issue to implement that; but for the time being I will have to release the update that include changes from: https://github.com/paul-nelson-baker/python-qtest-library/pull/1

**Comment by nikole-dunixi** [comment]
Here is the issue to track when the code is pushed to pypi, @bigoulours

**Comment by bigoulours** [comment]
Thanks! Anything new on this?

**Comment by nikole-dunixi** [comment]
@bigoulours Apologies for the delay. IRL responsibilities took priority and it seems like python's changed how it releases packages compared to how I did it way-back-when. It seems like I may have been doing something then that is now legacy, which might mean the package may go by the way-side in the future. In the meantime, this has been pushed and released

https://pypi.org/manage/project/qasymphony-qtest-library/release/0.2.2/
